"""Initial migration

Revision ID: 010140ca96fc
Revises: 
Create Date: 2025-11-26 10:14:03.072418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '010140ca96fc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
